language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
before_script:
- cd capsulefyweb
- python manage.py migrate
- python manage.py collectstatic
script:
- coverage run manage.py test
after_success:
- coveralls
- cd ..
notifications:
  email: false
services:
- postgresql
addons:
  postgresql: '9.6'
global:
- PGPORT=5432
#deploy:
#  provider: heroku
#  api_key:
#    master:
#      secure: ztNJTYFLHus1xf0FHI4PcLgQufCn24gvw7B1a59eYlUcx1NtsLiuoBy4hL32l+pFVvW2dInVcP4AIph5I2cUjr5ez1qa2hN4nb3A8z889u0YRkKfxCz94c61SOfcBhGhnXaliEK6ToF2EMWfqlIDrNb9kuXdMLh7yTB9PN39w8kTFaOcqXbkeTt1vDHgTFXJBQAQ0L0PT6szZ6Y7fu7LsRJ9V2DVTqe45OK6MTplazNtnCDOtPiGEhaira8Kh1nTjFOFZabKfrjCwDK3wL6T5zUNBeivklNJWlKENH9xtIG8yF9nNBM/8zKYF3c7nJmNE+wvZLpL1XLgRawah+8V2NZfvn3xUh3rTXA8Eythv5HzbPKwHWX04Te5ePkj2oSMIYh6Gas5XyUzp6uqLLzjbVUYmzLP4NEGZGjAEIhAr2ekHnsK4GStlTZuGD10LQwRVmpCfxb1eTK7R5s/WzVf/HxEMje8fb35eVpT2nyapgz8dsjuSKHslCh/38/aMlI8f9JWvxCGhL6akD0iJUKKi9Kgih3cB/5B1JYcLtCzaQmjNNmMWztaqImcqqEUNB8Dje+UOjEs6KQ6VyDOwN0qS17lSsmM+Y6bk3ZOudN1tp5YZ1vdzSLK1qUg8utHQujdmWNDGu8G29tkDCpHkJysKs4BB5LNus0lSZSI+so32gA=
#  app:
#    master: capsulefy
