language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
before_script:
- cd capsulefyweb
- python manage.py migrate
- python manage.py collectstatic
script:
- python manage.py test
notifications:
  email: false
services:
- postgresql
addons:
  postgresql: '9.6'
global:
- PGPORT=5432
deploy: &heroku
  provider: heroku
  api_key:
    master:
    secure: TrwmZVKJcW6qQx3D3qg+8SrndD2aGhCI22bIKbtvRy2g53SukSOoATWYPcY5Uif8KX3XjKZ8GSTDaS9jzmsD/XF5Iv9xlb1bZjpyrIG4WF7zyJSLISqa5l9IFGaBd8eYigwY43+HLqnBirnGN2xALwKU3b4C5HwQtFWuyjNXtLPbrZmy2vmxKdMVwmNM9F3w0rqzr5eTyfPaPTn2nIMzcJhTYGgVdKMVxe8U3iZmwdWE050qXi5pV8V8JoAX7/kHKqJOLSCthda7+poh4oTjMvR8CbZtheCTVVLQQyg8h3m/60Mc2jGy52XOKNHcWc+wnTngvDJvgL/5Z7SAw1+do6YrIzdvIcWezTBF0lk5D+1DBHwW/vWDRstM7NZ9+sEKbXkTa95VgYe8rgtVauE4PEQ38aNrhmTrrGXOuddMS8UNhPwMhOqRjsfHT9dXgM1jA9uHp52wqPjcpU9icU3cAOMEG77HX9berOMQWoFH3UsBsHvH4Bea7nSBvrxi3u8iUbezw3nSpPnEAMWToWECbui3PbiQ4OUaxqeXZheHGyUeDD3inrvrZ7nh5cdOIbOXADQxtp0uHmyDY4tLTS6F8ytYzFJxOaCLzESD8u/m0KCsh8NnkVlUeuKhZtyP4hg2oiJrmY6BUX4j6JKK1KnARZkcHNSvpvOvaRuYMb86j6g=
  app:
    master: capsulefy
