language: python
python:
    - 3.6.6
install:
    - pip install -r requirements.txt
before_script:
    - cd capsulefyweb
    - python manage.py migrate
script:
    - python manage.py test
notifications:
    email: false
services:
    - postgresql
addons:
    postgresql: "9.6"
global:
    - PGPORT=5432